### PR TITLE
Version 3.6.0

### PR DESCRIPTION
**Pull request by Daniele-rolli**
This version features

- Improved Markdown Support
- Drawing Block (#233)
- Fix for issue (#230) related to Collapsible headers
- Highlighter colors (#229)
- Fixed an import issue with Locked Notes
- Added French and Russian
- Added support for Ctrl + to zoom in. (#238)

### CODE REVIEW

**Comment by Daniele-rolli** [comment]
@all-contributors please add @o-l-a-v for platform

**Comment by Daniele-rolli** [comment]
@all-contributors please add @o-l-a-v for platform

**Comment by bigshans** [comment]
图片

The erase works but it is not very sensitive when the line is very thin or the draw is very small.

The translation I've updated.

No other issues have been found yet.

**Comment by eag75** [comment]
Bildschirmfoto vom 2024-09-04 17-43-41

I have noticed a small discrepancy in the appearance settings. Shouldn't left-aligned be on the left and right-aligned on the right?

Other than that, I haven't noticed any issues in the new version.

**Comment by Daniele-rolli** [comment]
Everything appears to be fixed. Tomorrow, I'll work on packaging the app and drafting the new release notes.

**Pull request merged**
