### PR TITLE
Fixes for version 3.7.0

### PR DESCRIPTION
**Pull request by Daniele-rolli**
- Fixed tables
- Added markdown import & export notifications

### CODE REVIEW

**Comment by bigshans** [comment]
The following content will cause parsing errors:

```markdown
---
kanban-plugin: board
---
```

**Comment by Daniele-rolli** [comment]
It's trying to parse an Obsidian plugin, which we don't currently support. We could consider adding a way to handle or ignore Obsidian plugins. I'll add the Kanban board as an idea to the roadmap since it might be worth implementing in the future.

**Comment by bigshans** [comment]
> It's trying to parse an Obsidian plugin, which we don't currently support. We could consider adding a way to handle or ignore Obsidian plugins. I'll add the Kanban board as an idea to the roadmap since it might be worth implementing in the future.

The following content will cause parsing errors too:

```markdown
---
---
```

图片

This is unrelated to whether it is an Obsidian plugin.

**Comment by Daniele-rolli** [comment]
In this case, I'll modify the code to parse `---` as horizontal rules, as that's how it's parsed in Markdown.

**Comment by Daniele-rolli** [comment]
I've added support for `---` and other methods to insert horizontal rules in the markdown parser with commit [7f1f0ec](https://github.com/Beaver-Notes/Beaver-Notes/commit/7f1f0ecfe1ead3b09ad8724e6e1b5bb49adcfd49).

**Comment by Daniele-rolli** [comment]
I think we might be ready for a release after all.

**Pull request merged**
