### PR TITLE
🇺🇦 Ukrainian + fixing quit

### PR DESCRIPTION
**Pull request by Daniele-rolli**
This should fix 'quit' once and for all. I was working on translations before addressing the issues in 'quit'; therefore, this pull request also features some new translations. I'll work on fixing the conflicts once we figure out the 'quit' on all platforms.

### CODE REVIEW

**Comment by bigshans** [comment]
`windowCloseHandler()` seems lost.

**Comment by Daniele-rolli** [comment]
What do you mean by 'lost'?

**Comment by Daniele-rolli** [comment]
I added a console.log to it, and upon closing the window, the log showed up, so it seems to be working.

```
async function windowCloseHandler(win) {
  await ipcMain.callRenderer(win, 'win:close');
  console.log('window closed');
}
```

**Comment by Daniele-rolli** [comment]
We could move `app.quit` into `windowCloseHandler()` just to make the code a bit tidier:

```
async function windowCloseHandler(win) {
  await ipcMain.callRenderer(win, 'win:close');
  app.quit();
}
```

**Comment by bigshans** [comment]
Maybe due to `revert`, some codes are reverted. I will rewrite some codes for this branch.

**Comment by Daniele-rolli** [comment]
You're right, I noticed it just now.

**Comment by Daniele-rolli** [comment]
I've moved some of the old code to this branch, try it out and let me know if it works because it now does on macOS

**Comment by bigshans** [comment]
And Chinese translation can be updated too. I have updated the translation on Tradura.

**Comment by Daniele-rolli** [comment]
Thanks for reminding me. I've already updated all the locales while adding Ukrainian. I think we might be ready to release version 3.2.0, if not today, then in the next couple of days.

**Comment by bigshans** [comment]
No more problems for me. Only the two need to be fixed.

**Comment by Daniele-rolli** [comment]
Everything seems fine, including translations. If you want, you can check the development branch and let me know if we can proceed.

**Comment by bigshans** [comment]
> Everything seems fine, including translations. If you want, you can check the development branch and let me know if we can proceed.

No, don't forget the `try/catch` of `windowCloseHandler` bro. I mentioned it above.

**Comment by Daniele-rolli** [comment]
gotcha you it now works fine I changed it from ```async function windowCloseHandler(win) {
  await ipcMain.callRenderer(win, 'win:close');
  app.quit();
}```
to 
```
async function windowCloseHandler(win) {
  try {
    await ipcMain.callRenderer(win, 'win:close');
  } catch (error) {
    console.error('Error handling window close:', error);
  } finally {
    app.quit();
  }
}
```

**Comment by bigshans** [comment]
> Got it, here's the revised version with improved grammar:
> 
> ```
> async function windowCloseHandler(win) {
>   await ipcMain.callRenderer(win, 'win:close');
>   app.quit();
> }
> ```
> 
> to
> 
> ```
> async function windowCloseHandler(win) {
>   try {
>     await ipcMain.callRenderer(win, 'win:close');
>   } catch (error) {
>     console.error('Error handling window close:', error);
>   } finally {
>     app.quit();
>   }
> }
> ```

And here can be this:

```javascript
  let canClosed = false;
  mainWindow.on('close', (e) => {
    if (canClosed) {
      return;
    }
    e.preventDefault();
    windowCloseHandler(mainWindow);
    canClosed = true;
 });
```

**Pull request merged**
