### PR TITLE
Version 3.5.0

### PR DESCRIPTION
**Pull request by Daniele-rolli**
### Changes

- Fixed focus mode (issue #214)
- Export / Import to GVFS (issue #214) - no auto sync support
- Improved Collapsible headings (@bigshans)
- Updated MathBlock real time rendering (issue #221)
- Importing Markdown files
- Updated electron from 28 to 31
- Subscript and Superscript 
- Footnotes
- Audio Notes
- Video Files
- Embeds (Website, Youtube videos, etc...)
- New Linux icon
- Alert pop-up for empty sync path or GVFS when trying to enable autosync.
- Drag to insert Files, Audios, Videos and Images
- Support for disk paths to insert Files, Images and Videos

### CODE REVIEW

**Comment by bigshans** [comment]
I got an error when I started to record audio.

图片

But this code runs fine on Firefox.

```js
          stream = await navigator.mediaDevices.getUserMedia({
            audio: true,
            video: false,
          });
```

This code also breaks on Vivaldi on my computer.

OS: Arch Linux
Desktop: Plasma 6 on Xorg

**Comment by bigshans** [comment]
footnote_bug

When you keep typing enter, it will keep eating the previous characters.

**Comment by Daniele-rolli** [comment]
Interesting. On macOS, there are no issues with requesting access to the microphone. I think it might be an issue specific to Electron. I'll do some investigating and report back. As for the issue with pressing Enter, I'll look into the extension and find out what's causing it.

**Comment by Daniele-rolli** [comment]
https://github.com/user-attachments/assets/0775323d-b93d-436f-a9b5-e9b239b8adf8

The footnotes seem to be working fine for me.

**Comment by bigshans** [comment]
> Screen.Recording.2024-07-26.at.2.41.11.PM.mov
> 
> The footnotes seem to be working fine for me.

Yes, I know. But you need to reproduce the operations in my gif. When toggling to paragraphs, the footnote is not parsed properly.

**Comment by Daniele-rolli** [comment]
Thanks for the clarification. I tried replicating the issue, and it doesn't seem to appear with any blocks like headings, quote blocks, etc. However, when I try to convert the paragraph to a code block, the footnote gets deleted, and turning it back into a paragraph doesn’t fix the problem. I’ll look into it further because it’s a pretty unusual bug.

> > Screen.Recording.2024-07-26.at.2.41.11.PM.mov
> > The footnotes seem to be working fine for me.
> 
> Yes, I know. But you need to reproduce the operations in my gif. When toggling to paragraphs, the footnote is not parsed properly.

**Comment by Daniele-rolli** [comment]
https://github.com/user-attachments/assets/ab7e1fba-ad00-40be-acb7-183810aac3e2

**Comment by Daniele-rolli** [comment]
> I got an error when I started to record audio.
> 
> 图片
> 
> But this code runs fine on Firefox.
> 
> ```js
>           stream = await navigator.mediaDevices.getUserMedia({
>             audio: true,
>             video: false,
>           });
> ```
> 
> This code also breaks on Vivaldi on my computer.
> 
> OS: Arch Linux Desktop: Plasma 6 on Xorg

Just out of pure curiosity, are you using PulseAudio or PipeWire? I’ve tested it on Ubuntu Desktop 24.04 ARM64, which uses PipeWire, and everything seems to work fine. I've read in some issues on the Electron GitHub that PulseAudio doesn’t play well with Electron.

**Comment by Daniele-rolli** [comment]
> I think it's the `[^1]` breaks anything.

It could be, but I can't manage to replicate the issue myself. I'll try replicating it on Ubuntu.

**Comment by Daniele-rolli** [comment]
> footnote_bug [ footnote_bug ](https://private-user-images.githubusercontent.com/26884666/352529615-82f439c8-84b2-42c5-89db-bbfed84f17c1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDA3OTUsIm5iZiI6MTcyMjAwMDQ5NSwicGF0aCI6Ii8yNjg4NDY2Ni8zNTI1Mjk2MTUtODJmNDM5YzgtODRiMi00MmM1LTg5ZGItYmJmZWQ4NGYxN2MxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWIwNjQ5YTRlNTA5ZGM4ODUwNDNlMzQyN2FiZWMwYjFhOGQ2YjU3OTNlZjJjNGZjMmExNjdhNTA2NzhhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvqxlzuOtOxa09bdkpvtpt3JOb2qmVAgvRHJpe93llU) [ ](https://private-user-images.githubusercontent.com/26884666/352529615-82f439c8-84b2-42c5-89db-bbfed84f17c1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDA3OTUsIm5iZiI6MTcyMjAwMDQ5NSwicGF0aCI6Ii8yNjg4NDY2Ni8zNTI1Mjk2MTUtODJmNDM5YzgtODRiMi00MmM1LTg5ZGItYmJmZWQ4NGYxN2MxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWIwNjQ5YTRlNTA5ZGM4ODUwNDNlMzQyN2FiZWMwYjFhOGQ2YjU3OTNlZjJjNGZjMmExNjdhNTA2NzhhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvqxlzuOtOxa09bdkpvtpt3JOb2qmVAgvRHJpe93llU)
> 
> When you keep typing enter, it will keep eating the previous characters.

Still, I can't replicate the issue. I tried on both Ubuntu 22.04 arm64 and macOS 14.5, but the footnote works fine in both cases and only disappears when trying to convert the paragraph into a code block. This behavior is expected, considering that the footnote is just an `<a>` tag, which isn't supported in code blocks, similar to how bold and italic formatting isn't supported.

**Comment by bigshans** [comment]
Maybe PulseAudio. I have both on my computer but usually, I control my audio driver though PulseAudio.

Replicate it is very simple. You can only **paste** this text `[^1]` on your editor, then you type the enter after `[^1]`, you will get it. Don't input it, it will auto-convert. Don't convert it at first time.

**Comment by Daniele-rolli** [comment]
I've just made a commit to partially fix the issue. Now, adding a space or pressing Enter after pasting text like [^1] in your editor doesn't do anything; however, [^1] still isn't automatically converted into a footnote.

**Comment by eag75** [comment]
I've added the German translation for version 3.5.0. When testing the developer branch, I noticed that the icon menu bar now has a scroll bar. Probably because you have added more icons. Does the menu bar have a fixed size? In my screenshot there would be more space compared to the whole window.

Bildschirmfoto vom 2024-07-27 11-48-16

**Comment by bigshans** [comment]
> I've added the German translation for version 3.5.0. When testing the developer branch, I noticed that the icon menu bar now has a scroll bar. Probably because you have added more icons. Does the menu bar have a fixed size? In my screenshot there would be more space compared to the whole window.
> 
> Bildschirmfoto vom 2024-07-27 11-48-16

You can turn on `expand page`.

**Comment by eag75** [comment]
> 
> You can turn on `expand page`.

Thx, that fix the problem.

**Comment by Daniele-rolli** [comment]
I think we might be ready for a final release, given there are no major issues. The only thing left to do is to document the markdown importer, audio notes, video files, embeds (websites, YouTube videos, etc.), superscript, subscript, and footnotes, which I'll take care of.

**Comment by bigshans** [comment]
I've updated the Chinese translations. You can sync it.

**Pull request merged**
