### PR TITLE
fix: remove the leaving process after quit

### PR DESCRIPTION
**Pull request by bigshans**
When the auto sync fails, the application will leave a process, and you can't restart the application.

This PR will add a new hook to manage the window `close` event. Then all handlers can be executed, and all errors can't affect the close event.

### CODE REVIEW

**Comment by Daniele-rolli** [comment]
I see what you mean, but ever since this commit was merged, I've noticed that the app doesn't close properly anymore, at least not on macOS.

https://github.com/Beaver-Notes/Beaver-Notes/assets/67503004/bfbc68f8-65af-421b-bb62-50fca534bde4

**Comment by bigshans** [comment]
> I see what you mean, but ever since this commit was merged, I've noticed that the app doesn't close properly anymore, at least not on macOS.

Does have any errors showing or any more info? I can't reproduce it on my platform.

**Comment by bigshans** [comment]
I will revert it and open a new one.

**Comment by Daniele-rolli** [comment]
I might have an idea on how to fix it since the error seems to be platform-specific, and both the console and terminal don't report any issues.

**Comment by bigshans** [comment]
> I might have an idea on how to fix it since the error seems to be platform-specific, and both the console and terminal don't report any issues.

Can you open a PR for me to test together?

**Comment by Daniele-rolli** [comment]
Yep, as soon as, but it's just a theory so I'll try it and then open a PR. From what I understand ipcRenderer calls for to close the window:

```
async function windowCloseHandler(win) {
  await ipcMain.callRenderer(win, 'win:close');
}

```

while macOS waits for this to close the window:

```
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
```

**Comment by bigshans** [comment]
Key logic is here:

```javascript
  let canClosed = false;
  mainWindow.on('close', (e) => {
    if (canClosed) {
      return;
    }
    e.preventDefault();
    windowCloseHandler()
      .then(() => {
        app.quit();
      })
      .catch((e) => {
        console.error(e);
        app.exit(1);
      });
    canClosed = true;
  });
```

Maybe you can test put `canClosed = true` before `windowCloseHandler`?

**Comment by Daniele-rolli** [comment]
This seems to fix the issue on macOS. Try it and let me know if it works on Linux/Windows too:

```
  let canClosed = false;
  mainWindow.on('close', (e) => {
    if (canClosed) {
      return;
    }
    e.preventDefault();
    windowCloseHandler(mainWindow)
      .catch((e) => {
        console.error(e);
      })
      .finally(() => {
        mainWindow.close();
        app.quit();
      });
    canClosed = true;
  });
```

**Comment by bigshans** [comment]
> This seems to fix the issue on macOS. Try it and let me know if it works on Linux/Windows too:
> 
> ```
>   let canClosed = false;
>   mainWindow.on('close', (e) => {
>     if (canClosed) {
>       return;
>     }
>     e.preventDefault();
>     windowCloseHandler(mainWindow)
>       .catch((e) => {
>         console.error(e);
>       })
>       .finally(() => {
>         mainWindow.close();
>         app.quit();
>       });
>     canClosed = true;
>   });
> ```

Yes, it works. Even `app.quit()` is not here, it also works. But why need `app.quit()` in here?

**Comment by bigshans** [comment]
I find the document about `window-all-closed`:

> If you do not subscribe to this event and all windows are closed, the default behavior is to quit the app; however, if you subscribe, you control whether the app quits or not. If the user pressed Cmd + Q, or the developer called app.quit(), Electron will first try to close all the windows and then emit the will-quit event, and in this case the window-all-closed event would not be emitted.

I guess here :

>  If the user pressed Cmd + Q, or the developer called app.quit(), Electron will first try to close all the windows and then emit the will-quit event, and in this case the window-all-closed event would not be emitted.

**Comment by Daniele-rolli** [comment]
Yep, as I was about to say, we called app.quit() to trigger the window-all-closed event that Mac OS requires to quit:
```
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
```

**Pull request merged**
