### PR TITLE
Add authorization system

### PR DESCRIPTION
**Pull request by bigshans**
Test Steps:

1. Request token by `curl`. The confirm dialog will pop up in the editor.
2. Confirm it will create the token. The token will be displayed in the terminal.
3. Request `/confirm-auth` with the token. If it echos `passed`, it means the verification is passed.

There are commands:

Request for token.
```shell
curl --location 'http://localhost:3000/request-auth' \
--header 'Content-Type: application/json' \
--data '{
    "platform": "postman",
    "id": "4061716c-7cfd-4de2-acfd-d2c5376119cb"
}'
```

Request `/confirm-auth`. Replace `your-token` with the token you get.
```shell
curl --location --request GET 'http://localhost:3000/confirm-auth' \
--header 'Authorization: Bearer your-token' \
--header 'Content-Type: application/json' \
--data '{
    "platform": "postman",
    "id": "4061716c-7cfd-4de2-acfd-d2c5376119cb"
}'
```

The encryption algorithm uses `aes-256-gcm` and I implement it with `crypto` module. The token will record information about the id, client id, token's name, permissions, created time, expired time, and status of the token.

The verification is passed if and only if the permission fully meets the API requirements, is recorded in the application, and the status is active (means `status` equal to 1) and has not expired (`expiredTime` equals 0, which is considered never expired).

### CODE REVIEW

**Comment by Daniele-rolli** [comment]
It all works fine; the only issue I see is that the add-note is configured to not request the token for some reason.

**Comment by bigshans** [comment]
> It all works fine; the only issue I see is that the add-note is configured to not request the token for some reason.

Because I'm not configured with it. I just added some API for testing. Now I've added it so you can try it.

**Comment by Daniele-rolli** [comment]
I was documenting the API and I think you might want to take a look at the auth because `note:add` doesn't really work. It always says 'No such permission!' If you could look into it, I'd be grateful.

**Comment by bigshans** [comment]
> I was documenting the API and I think you might want to take a look at the auth because `note:add` doesn't really work. It always says 'No such permission!' If you could look into it, I'd be grateful.

Because the permissions granted here are `label:add,note:delete` and there is no `note:add` permission, the prompt is correct. However, this should be controlled by the user. I'm improving the UI now.

**Pull request merged**
